spring.application.name=artisanMarket

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/artisan_market_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Jwt configuration
jwt.secret=

# Google
google.client.id=

# VNPay Configuration (Sandbox)
vnpay.tmn-code=
vnpay.hash-secret=
vnpay.url=
vnpay.return-url=
vnpay.frontend-return-url=
vnpay.api-url=

# Cloudinary Configuration
cloudinary.cloud-name=
cloudinary.api-key=
cloudinary.api-secret=

# Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Reset Password Frontend URL
app.reset-password-url=http://localhost:5173/reset-password

# Verify Email Frontend URL
app.verify-email-url=http://localhost:5173/verify-email